spring.application.name=PRD

server.port=9090
server.servlet.context-path=/prd

logging.level.root=info

spell.checker.owner-name=Tech Pioneers Hub
spell.checker.version=V1.0


# DB Configs
db.username=admin
db.password=THS@12HHSMdas
db.database=prodDb
db.url=jdbc:mysql://192.168.1.210:3306/prodDb
db.connection-pool-properties.max-open-connections=150
db.connection-pool-properties.max-idle-connections=80
db.connection-pool-properties.timeout=200